"""add studio workflow

Revision ID: 0c4793a009a1
Revises: bb4191cbce41
Create Date: 2026-09-29 00:13:46.147311
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0c4793a009a1"
down_revision: str | None = "bb4191cbce41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "add_ons",
        sa.Column("studio_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("add_on_type", sa.String(length=30), nullable=False),
        sa.Column("default_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["studio_id"], ["studios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_add_ons_add_on_type"), "add_ons", ["add_on_type"], unique=False)
    op.create_index(op.f("ix_add_ons_is_active"), "add_ons", ["is_active"], unique=False)
    op.create_index(op.f("ix_add_ons_studio_id"), "add_ons", ["studio_id"], unique=False)
    op.create_table(
        "service_packages",
        sa.Column("studio_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("service_type", sa.String(length=30), nullable=False),
        sa.Column("base_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("deliverables", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["studio_id"], ["studios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_packages_is_active"), "service_packages", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_service_packages_service_type"), "service_packages", ["service_type"], unique=False
    )
    op.create_index(
        op.f("ix_service_packages_studio_id"), "service_packages", ["studio_id"], unique=False
    )
    op.create_table(
        "quotation_items",
        sa.Column("quotation_id", sa.Uuid(), nullable=False),
        sa.Column("item_type", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["quotation_id"], ["quotations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_quotation_items_item_type"), "quotation_items", ["item_type"], unique=False
    )
    op.create_index(
        op.f("ix_quotation_items_quotation_id"), "quotation_items", ["quotation_id"], unique=False
    )
    op.create_table(
        "delivery_items",
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_items_invoice_id"), "delivery_items", ["invoice_id"], unique=False
    )
    op.create_index(op.f("ix_delivery_items_status"), "delivery_items", ["status"], unique=False)
    op.add_column("events", sa.Column("original_date", sa.Date(), nullable=True))
    op.add_column("events", sa.Column("tentative_date", sa.Date(), nullable=True))
    op.add_column("events", sa.Column("postpone_reason", sa.Text(), nullable=True))
    op.add_column(
        "invoices",
        sa.Column(
            "advance_paid", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
    )
    op.add_column("invoices", sa.Column("notes", sa.Text(), nullable=True))
    op.add_column("studios", sa.Column("phone", sa.String(length=30), nullable=True))
    op.add_column("studios", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column("studios", sa.Column("address", sa.Text(), nullable=True))
    op.add_column("studios", sa.Column("brand_color_primary", sa.String(length=7), nullable=True))
    op.add_column("studios", sa.Column("brand_color_secondary", sa.String(length=7), nullable=True))
    op.add_column("studios", sa.Column("bank_name", sa.String(length=120), nullable=True))
    op.add_column("studios", sa.Column("bank_account_holder", sa.String(length=120), nullable=True))
    op.add_column("studios", sa.Column("bank_account_number", sa.String(length=80), nullable=True))
    op.add_column("studios", sa.Column("bank_branch", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("studios", "bank_branch")
    op.drop_column("studios", "bank_account_number")
    op.drop_column("studios", "bank_account_holder")
    op.drop_column("studios", "bank_name")
    op.drop_column("studios", "brand_color_secondary")
    op.drop_column("studios", "brand_color_primary")
    op.drop_column("studios", "address")
    op.drop_column("studios", "email")
    op.drop_column("studios", "phone")
    op.drop_column("invoices", "notes")
    op.drop_column("invoices", "advance_paid")
    op.drop_column("events", "postpone_reason")
    op.drop_column("events", "tentative_date")
    op.drop_column("events", "original_date")
    op.drop_index(op.f("ix_delivery_items_status"), table_name="delivery_items")
    op.drop_index(op.f("ix_delivery_items_invoice_id"), table_name="delivery_items")
    op.drop_table("delivery_items")
    op.drop_index(op.f("ix_quotation_items_quotation_id"), table_name="quotation_items")
    op.drop_index(op.f("ix_quotation_items_item_type"), table_name="quotation_items")
    op.drop_table("quotation_items")
    op.drop_index(op.f("ix_service_packages_studio_id"), table_name="service_packages")
    op.drop_index(op.f("ix_service_packages_service_type"), table_name="service_packages")
    op.drop_index(op.f("ix_service_packages_is_active"), table_name="service_packages")
    op.drop_table("service_packages")
    op.drop_index(op.f("ix_add_ons_studio_id"), table_name="add_ons")
    op.drop_index(op.f("ix_add_ons_is_active"), table_name="add_ons")
    op.drop_index(op.f("ix_add_ons_add_on_type"), table_name="add_ons")
    op.drop_table("add_ons")
    # ### end Alembic commands ###
