"""add bookings table

Revision ID: 8f7158ff03e2
Revises: 20260927_0001
Create Date: 2026-09-28 23:07:28.200944
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8f7158ff03e2'
down_revision: Union[str, None] = '20260927_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('invoices_invoice_number_key'), 'invoices', type_='unique')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.drop_constraint(op.f('studios_subdomain_key'), 'studios', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('studios_subdomain_key'), 'studios', ['subdomain'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_unique_constraint(op.f('invoices_invoice_number_key'), 'invoices', ['invoice_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
