"""store quotation details

Revision ID: bb4191cbce41
Revises: 10c6d455a438
Create Date: 2026-09-28 23:47:42.892554
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "bb4191cbce41"
down_revision: str | None = "10c6d455a438"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quotations", sa.Column("package_name", sa.String(length=120), nullable=True))
    op.add_column("quotations", sa.Column("service_type", sa.String(length=30), nullable=True))
    op.add_column("quotations", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("quotations", "notes")
    op.drop_column("quotations", "service_type")
    op.drop_column("quotations", "package_name")
    # ### end Alembic commands ###
