/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardDeliveriesRouteImport } from './routes/dashboard.deliveries'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard.finance'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardInvoicesRouteImport } from './routes/dashboard.invoices'
import { Route as DashboardPackagesRouteImport } from './routes/dashboard.packages'
import { Route as DashboardPostponedRouteImport } from './routes/dashboard.postponed'
import { Route as DashboardQuotationsRouteImport } from './routes/dashboard.quotations'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardQuotationsIndexRouteImport } from './routes/dashboard.quotations.index'
import { Route as DashboardQuotationsNewRouteImport } from './routes/dashboard.quotations.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveriesRoute = DashboardDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvoicesRoute = DashboardInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPackagesRoute = DashboardPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPostponedRoute = DashboardPostponedRouteImport.update({
  id: '/postponed',
  path: '/postponed',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotationsRoute = DashboardQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuotationsIndexRoute =
  DashboardQuotationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardQuotationsRoute,
  } as any)
const DashboardQuotationsNewRoute = DashboardQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardQuotationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/postponed': typeof DashboardPostponedRoute
  '/dashboard/quotations': typeof DashboardQuotationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/quotations/new': typeof DashboardQuotationsNewRoute
  '/dashboard/quotations/': typeof DashboardQuotationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/postponed': typeof DashboardPostponedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/quotations/new': typeof DashboardQuotationsNewRoute
  '/dashboard/quotations': typeof DashboardQuotationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/deliveries': typeof DashboardDeliveriesRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/invoices': typeof DashboardInvoicesRoute
  '/dashboard/packages': typeof DashboardPackagesRoute
  '/dashboard/postponed': typeof DashboardPostponedRoute
  '/dashboard/quotations': typeof DashboardQuotationsRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/quotations/new': typeof DashboardQuotationsNewRoute
  '/dashboard/quotations/': typeof DashboardQuotationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/deliveries'
    | '/dashboard/finance'
    | '/dashboard/help'
    | '/dashboard/invoices'
    | '/dashboard/packages'
    | '/dashboard/postponed'
    | '/dashboard/quotations'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/'
    | '/dashboard/quotations/new'
    | '/dashboard/quotations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/deliveries'
    | '/dashboard/finance'
    | '/dashboard/help'
    | '/dashboard/invoices'
    | '/dashboard/packages'
    | '/dashboard/postponed'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard'
    | '/dashboard/quotations/new'
    | '/dashboard/quotations'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/signup'
    | '/dashboard/billing'
    | '/dashboard/calendar'
    | '/dashboard/deliveries'
    | '/dashboard/finance'
    | '/dashboard/help'
    | '/dashboard/invoices'
    | '/dashboard/packages'
    | '/dashboard/postponed'
    | '/dashboard/quotations'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/'
    | '/dashboard/quotations/new'
    | '/dashboard/quotations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deliveries': {
      id: '/dashboard/deliveries'
      path: '/deliveries'
      fullPath: '/dashboard/deliveries'
      preLoaderRoute: typeof DashboardDeliveriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invoices': {
      id: '/dashboard/invoices'
      path: '/invoices'
      fullPath: '/dashboard/invoices'
      preLoaderRoute: typeof DashboardInvoicesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/packages': {
      id: '/dashboard/packages'
      path: '/packages'
      fullPath: '/dashboard/packages'
      preLoaderRoute: typeof DashboardPackagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/postponed': {
      id: '/dashboard/postponed'
      path: '/postponed'
      fullPath: '/dashboard/postponed'
      preLoaderRoute: typeof DashboardPostponedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotations': {
      id: '/dashboard/quotations'
      path: '/quotations'
      fullPath: '/dashboard/quotations'
      preLoaderRoute: typeof DashboardQuotationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quotations/': {
      id: '/dashboard/quotations/'
      path: '/'
      fullPath: '/dashboard/quotations/'
      preLoaderRoute: typeof DashboardQuotationsIndexRouteImport
      parentRoute: typeof DashboardQuotationsRoute
    }
    '/dashboard/quotations/new': {
      id: '/dashboard/quotations/new'
      path: '/new'
      fullPath: '/dashboard/quotations/new'
      preLoaderRoute: typeof DashboardQuotationsNewRouteImport
      parentRoute: typeof DashboardQuotationsRoute
    }
  }
}

interface DashboardQuotationsRouteChildren {
  DashboardQuotationsNewRoute: typeof DashboardQuotationsNewRoute
  DashboardQuotationsIndexRoute: typeof DashboardQuotationsIndexRoute
}

const DashboardQuotationsRouteChildren: DashboardQuotationsRouteChildren = {
  DashboardQuotationsNewRoute: DashboardQuotationsNewRoute,
  DashboardQuotationsIndexRoute: DashboardQuotationsIndexRoute,
}

const DashboardQuotationsRouteWithChildren =
  DashboardQuotationsRoute._addFileChildren(DashboardQuotationsRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardDeliveriesRoute: typeof DashboardDeliveriesRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardInvoicesRoute: typeof DashboardInvoicesRoute
  DashboardPackagesRoute: typeof DashboardPackagesRoute
  DashboardPostponedRoute: typeof DashboardPostponedRoute
  DashboardQuotationsRoute: typeof DashboardQuotationsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardDeliveriesRoute: DashboardDeliveriesRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardInvoicesRoute: DashboardInvoicesRoute,
  DashboardPackagesRoute: DashboardPackagesRoute,
  DashboardPostponedRoute: DashboardPostponedRoute,
  DashboardQuotationsRoute: DashboardQuotationsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
